### ISSUE TITLE
Improper empty block and unknown field (wrong indentation) pass validation but fail on application

### ISSUE THREAD

**Issue by allen-pattern** [willthames/kubernetes-validate#31]
YAML like the following:

```yaml
        - name: redis
          image: redis:latest
          resources:
          requests:
            cpu: 50m
            memory: 256Mi
```

(rather than
```yaml
        - name: redis
          image: redis:latest
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
```
 \- note indentation) passes validation, but fails upon application with the error `strict decoding error: unknown field "spec.template.spec.containers[0].requests"`
